name: CI

on:
  push:
    branches:
      - main
      - wip-github-ci
  pull_request:
    branches:
      - main

# cancel in-progress job when a new push is performed
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    strategy:
      matrix:
        version: [4.14.1]


    runs-on: ubuntu-22.04

    timeout-minutes: 5
    steps:
    - run: mkdir -p rems-project

    - uses: actions/checkout@v3
      with:
        path: rems-project/casemate

    - name: System dependencies (ubuntu)
      run: |
        sudo apt update
        sudo apt install build-essential

    - name: Configure
      working-directory: rems-project/casemate
      run: |
        ./configure

    - name: Build all
      working-directory: rems-project/casemate
      run: |
        make

    - name: Run tests
      working-directory: rems-project/casemate
      run: |
        make checks
